### ISSUE TITLE
feat(server): add blur images for user profiles

### ISSUE THREAD

**Issue by Jes015** [CulinaryAlchemy/CulinaryAlchemy#209]
Backend:

- [ ] add the fields **avatarBlur** and **headerBlur** to upload blur images for the avatar and header fields of the user. These fields should be stored on our image server.

**Comment by Huilensolis** [comment]
please specify the images sizes and the image formats, so I configure it in the backend ; )

**Comment by Jes015** [comment]
> please specify the images sizes and the image formats, so I configure it in the backend ; ) @Jes015

20x20 px
